### PR TITLE
Enable push command to read filenames from pipe

### PR DESCRIPTION
**Pull request by yurybond**
Enable pipe for push command so you can use the following command line
`git diff HEAD --name-only --diff-filter=ACM | force push`

It will allow you to push files that were modified since the last commit.

### CODE REVIEW

**Comment by cwarden** [comment]
Thanks, @yurybond.  Is there any benefit over `git diff HEAD --name-only --diff-filter=ACM | xargs force push`?

**Comment by yurybond** [comment]
@cwarden Did you see updates of my latest comment? There some issues that does not allow to use `xargs`: it is not supported on windows, issues with files that have space in filename. 
So my pull request will not be useless, at least for me))

**Comment by yurybond** [comment]
@cwarden Do you have any thoughts my pull request

**Comment by cwarden** [comment]
@yurybond, thanks for the use-case details.  Windows not having a (commonly used) xargs equivalent is a valid argument.  Newline separated input to xargs can be handled with `--delimiter`.

I don't really like having `force push` just wait for input if no parameters are passed.  I'd prefer to add an explicit parameter to accept a list of files from a file and using the common convention of `-` to use stdin as the file, e.g. `git diff HEAD --name-only --diff-filter=ACM | force push -f -`

**Comment by yurybond** [comment]
@cwarden I will update a code to use `-` for stdin. Thanks for your feedback.

**Comment by yurybond** [comment]
@cwarden Could you please review changes I made? Now it should work using the following command
`git diff HEAD --name-only --diff-filter=ACM | force push -f -`

**Comment by cwarden** [comment]
Thanks, @yurybond. I squashed the commits and simplified the code a bit in 0c7b9e00ecc1b4be3aa903e1f5ccf7d1618bd40c, and merged to master in 7aab306d5f799ae096bdb4dbf0ff20a11f538a66.

**Pull request closed without merging**
